# Self-contained stub: cross-Cython types -> Any (auto-postprocessed from stubgen-pyx)
from typing import Any, Callable

def account_type_from_str(value: str) -> Any:
    ...

def account_type_to_str(value: Any) -> str:
    ...

def aggregation_source_from_str(value: str) -> Any:
    ...

def aggregation_source_to_str(value: Any) -> str:
    ...

def aggressor_side_from_str(value: str) -> Any:
    ...

def aggressor_side_to_str(value: Any) -> str:
    ...

def asset_class_from_str(value: str) -> Any:
    ...

def asset_class_to_str(value: Any) -> str:
    ...

def instrument_class_from_str(value: str) -> Any:
    ...

def instrument_class_to_str(value: Any) -> str:
    ...

def bar_aggregation_from_str(value: str) -> Any:
    ...

def bar_aggregation_to_str(value: Any) -> str:
    ...

def book_action_from_str(value: str) -> Any:
    ...

def book_action_to_str(value: Any) -> str:
    ...

def book_type_from_str(value: str) -> Any:
    ...

def book_type_to_str(value: Any) -> str:
    ...

def contingency_type_from_str(value: str) -> Any:
    ...

def contingency_type_to_str(value: Any) -> str:
    ...

def currency_type_from_str(value: str) -> Any:
    ...

def currency_type_to_str(value: Any) -> str:
    ...

def instrument_close_type_from_str(value: str) -> Any:
    ...

def instrument_close_type_to_str(value: Any) -> str:
    ...

def liquidity_side_from_str(value: str) -> Any:
    ...

def liquidity_side_to_str(value: Any) -> str:
    ...

def market_status_from_str(value: str) -> Any:
    ...

def market_status_to_str(value: Any) -> str:
    ...

def market_status_action_from_str(value: str) -> Any:
    ...

def market_status_action_to_str(value: Any) -> str:
    ...

def oms_type_from_str(value: str) -> Any:
    ...

def oms_type_to_str(value: Any) -> str:
    ...

def option_kind_from_str(value: str) -> Any:
    ...

def option_kind_to_str(value: Any) -> str:
    ...

def oto_trigger_mode_from_str(value: str) -> Any:
    ...

def oto_trigger_mode_to_str(value: Any) -> str:
    ...

def order_side_from_str(value: str) -> Any:
    ...

def order_side_to_str(value: Any) -> str:
    ...

def order_status_from_str(value: str) -> Any:
    ...

def order_status_to_str(value: Any) -> str:
    ...

def order_type_from_str(value: str) -> Any:
    ...

def order_type_to_str(value: Any) -> str:
    ...

def record_flag_from_str(value: str) -> Any:
    ...

def record_flag_to_str(value: Any) -> str:
    ...

def position_side_from_str(value: str) -> Any:
    ...

def position_side_to_str(value: Any) -> str:
    ...

def position_adjustment_type_from_str(value: str) -> Any:
    ...

def position_adjustment_type_to_str(value: Any) -> str:
    ...

def price_type_from_str(value: str) -> Any:
    ...

def price_type_to_str(value: Any) -> str:
    ...

def time_in_force_from_str(value: str) -> Any:
    ...

def time_in_force_to_str(value: Any) -> str:
    ...

def trading_state_from_str(value: str) -> Any:
    ...

def trading_state_to_str(value: Any) -> str:
    ...

def trailing_offset_type_from_str(value: str) -> Any:
    ...

def trailing_offset_type_to_str(value: Any) -> str:
    ...

def trigger_type_from_str(value: str) -> Any:
    ...

def trigger_type_to_str(value: Any) -> str:
    ...

def account_type_to_pyo3(value: Any):
    ...

def order_side_to_pyo3(value: Any):
    ...

def order_type_to_pyo3(value: Any):
    ...

def order_status_to_pyo3(value: Any):
    ...

def time_in_force_to_pyo3(value: Any):
    ...

def trigger_type_to_pyo3(value: Any):
    ...

def trailing_offset_type_to_pyo3(value: Any):
    ...

def contingency_type_to_pyo3(value: Any):
    ...

def order_side_from_pyo3(value: Any) -> Any:
    ...

def order_type_from_pyo3(value: Any) -> Any:
    ...

def order_status_from_pyo3(value: Any) -> Any:
    ...

def time_in_force_from_pyo3(value: Any) -> Any:
    ...

def liquidity_side_from_pyo3(value: Any) -> Any:
    ...

def contingency_type_from_pyo3(value: Any) -> Any:
    ...

def position_side_from_pyo3(value: Any) -> Any:
    ...