"""Minimal type stubs for nautilus_trader.model.objects.

Self-contained: no imports from other Cython modules.
Cross-module types (Currency, InstrumentId, etc.) are annotated as Any.
"""

import decimal
from typing import Any


FIXED_PRECISION: int


class AccountBalance:
    total: Any  # Money
    locked: Any  # Money
    free: Any  # Money
    currency: Any  # Currency
    def __init__(self, total: Any, locked: Any, free: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def copy(self) -> AccountBalance: ...
    @staticmethod
    def from_dict(values: dict[str, Any]) -> AccountBalance: ...
    def to_dict(self) -> dict[str, Any]: ...


class Currency:
    code: str
    name: str
    precision: int
    iso4217: int
    currency_type: Any
    def __init__(
        self,
        code: str,
        precision: int,
        iso4217: int,
        name: str,
        currency_type: Any,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def from_internal_map(code: str) -> Currency | None: ...
    @staticmethod
    def from_str(code: str, strict: bool = ...) -> Any: ...
    @staticmethod
    def is_crypto(code: str) -> bool: ...
    @staticmethod
    def is_fiat(code: str) -> bool: ...
    @staticmethod
    def register(currency: Any, overwrite: bool = ...) -> None: ...


class MarginBalance:
    initial: Any  # Money
    maintenance: Any  # Money
    instrument_id: Any  # InstrumentId
    def __init__(self, initial: Any, maintenance: Any, instrument_id: Any = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def copy(self) -> MarginBalance: ...
    @staticmethod
    def from_dict(values: dict[str, Any]) -> MarginBalance: ...
    def to_dict(self) -> dict[str, Any]: ...


class Money:
    currency: Any  # Currency
    raw: int
    def __init__(self, value: float | None, currency: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __add__(self, other: Any) -> Money | decimal.Decimal | float: ...
    def __radd__(self, other: Any) -> Money | decimal.Decimal | float: ...
    def __sub__(self, other: Any) -> Money | decimal.Decimal | float: ...
    def __rsub__(self, other: Any) -> Money | decimal.Decimal | float: ...
    def __mul__(self, other: Any) -> decimal.Decimal | float: ...
    def __rmul__(self, other: Any) -> decimal.Decimal | float: ...
    def __truediv__(self, other: Any) -> decimal.Decimal | float: ...
    def __rtruediv__(self, other: Any) -> decimal.Decimal | float: ...
    def __floordiv__(self, other: Any) -> decimal.Decimal | float: ...
    def __rfloordiv__(self, other: Any) -> decimal.Decimal | float: ...
    def __mod__(self, other: Any) -> decimal.Decimal | float: ...
    def __rmod__(self, other: Any) -> decimal.Decimal | float: ...
    def __neg__(self) -> Money: ...
    def __pos__(self) -> Money: ...
    def __abs__(self) -> Money: ...
    def __round__(self, ndigits: int | None = ...) -> decimal.Decimal: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def as_decimal(self) -> decimal.Decimal: ...
    def as_double(self) -> float: ...
    @staticmethod
    def from_decimal(amount: decimal.Decimal, currency: Any) -> Money: ...
    @staticmethod
    def from_raw(raw: int, currency: Any) -> Money: ...
    @staticmethod
    def from_str(value: str) -> Money: ...
    def to_formatted_str(self) -> str: ...


class Price:
    precision: int
    raw: int
    def __init__(self, value: float, precision: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __add__(self, other: Any) -> Price | decimal.Decimal | float: ...
    def __radd__(self, other: Any) -> Price | decimal.Decimal | float: ...
    def __sub__(self, other: Any) -> Price | decimal.Decimal | float: ...
    def __rsub__(self, other: Any) -> Price | decimal.Decimal | float: ...
    def __mul__(self, other: Any) -> decimal.Decimal | float: ...
    def __rmul__(self, other: Any) -> decimal.Decimal | float: ...
    def __truediv__(self, other: Any) -> decimal.Decimal | float: ...
    def __rtruediv__(self, other: Any) -> decimal.Decimal | float: ...
    def __floordiv__(self, other: Any) -> decimal.Decimal | float: ...
    def __rfloordiv__(self, other: Any) -> decimal.Decimal | float: ...
    def __mod__(self, other: Any) -> decimal.Decimal | float: ...
    def __rmod__(self, other: Any) -> decimal.Decimal | float: ...
    def __neg__(self) -> Price: ...
    def __pos__(self) -> Price: ...
    def __abs__(self) -> Price: ...
    def __round__(self, ndigits: int | None = ...) -> decimal.Decimal: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def as_decimal(self) -> decimal.Decimal: ...
    def as_double(self) -> float: ...
    @staticmethod
    def from_decimal(value: decimal.Decimal) -> Price: ...
    @staticmethod
    def from_int(value: int) -> Price: ...
    @staticmethod
    def from_raw(raw: int, precision: int) -> Price: ...
    @staticmethod
    def from_str(value: str) -> Price: ...
    def to_formatted_str(self) -> str: ...


class Quantity:
    precision: int
    raw: int
    def __init__(self, value: float, precision: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __add__(self, other: Any) -> Quantity | decimal.Decimal | float: ...
    def __radd__(self, other: Any) -> Quantity | decimal.Decimal | float: ...
    def __sub__(self, other: Any) -> Quantity | decimal.Decimal | float: ...
    def __rsub__(self, other: Any) -> Quantity | decimal.Decimal | float: ...
    def __mul__(self, other: Any) -> decimal.Decimal | float: ...
    def __rmul__(self, other: Any) -> decimal.Decimal | float: ...
    def __truediv__(self, other: Any) -> decimal.Decimal | float: ...
    def __rtruediv__(self, other: Any) -> decimal.Decimal | float: ...
    def __floordiv__(self, other: Any) -> decimal.Decimal | float: ...
    def __rfloordiv__(self, other: Any) -> decimal.Decimal | float: ...
    def __mod__(self, other: Any) -> decimal.Decimal | float: ...
    def __rmod__(self, other: Any) -> decimal.Decimal | float: ...
    def __neg__(self) -> decimal.Decimal: ...
    def __pos__(self) -> Quantity: ...
    def __abs__(self) -> Quantity: ...
    def __round__(self, ndigits: int | None = ...) -> decimal.Decimal: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def as_decimal(self) -> decimal.Decimal: ...
    def as_double(self) -> float: ...
    @staticmethod
    def from_decimal(value: decimal.Decimal) -> Quantity: ...
    @staticmethod
    def from_int(value: int) -> Quantity: ...
    @staticmethod
    def from_raw(raw: int, precision: int) -> Quantity: ...
    @staticmethod
    def from_str(value: str) -> Quantity: ...
    @staticmethod
    def raw_to_f64(raw: int) -> float: ...
    def saturating_sub(self, other: Quantity) -> Quantity: ...
    def to_formatted_str(self) -> str: ...
    @staticmethod
    def zero(precision: int = ...) -> Quantity: ...
